version: '3'
services:
  ret2love:
    build: .
    image: ret2love
    container_name: ret2love
    ports:
      - 5000:5000
    environment:
      
      PORT: 5000
    
    healthcheck:
      test: ["CMD", "true"]
      interval: 1s
      timeout: 1s
      retries: 3